<?php

/**
 * PluginsfSympalGalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfSympalGallery
 * @subpackage model
 * @author     Philipp A. Mohrenweiser <phiamo@gmail.com>
 */
class PluginsfSympalGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfSympalGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfSympalGallery');
    }
}