<?php

/**
 * PluginsfSympalGallerySlideTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSympalGallerySlideTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfSympalGallerySlideTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfSympalGallerySlide');
    }
}