<?php

/**
 * PluginsfSympalGallerySlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sfSympalGallery
 * @subpackage model
 * @author     Philipp A. Mohrenweiser <phiamo@gmail.com>
 */
class PluginsfSympalGallerySlotTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfSympalGallerySlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfSympalGallerySlot');
    }
}