<?php

/**
 * sfValidatorSympalGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfSympalGallery
 * @subpackage model
 * @author     Philipp A. Mohrenweiser <phiamo@gmail.com>
 */
class sfWidgetFormSympalGallery extends sfWidgetFormTextArea{
}