all:
  sympal_config:
    content_types:
      sfSympalGallery:
        content_templates:
          default_view:
            template:     sfSympalGallery/view
    content_slot_types:
      Gallery:
        label: Gallery
        form: sfSympalGallerySlotForm
        form_renderer: sympal_gallery/slot_editor_form
      #  widget_class: MySlotTypeWidget          default: sfWidgetFormSympalXXXXXXType
      #  widget_options: []
      #  validator_class: MySlotTypeValidator    default: sfValidatorFormSympalXXXXXXType
      #  validator_options: []
      #  transformers:    []
        filters: [inline_object]
      
  inline_object:
    types:
      gallery:   sfSympalInlineObjectGallery
      
  content_filter:
    filters:
      gallery:
        class:      sfContentFilterGallery
        cache:      false
        options:    []

  sympal_gallery:
    asset_class: sfSympalAsset
    gallery_renderers:
      simple: sympal_gallery/view
      ajax_slider: sympal_gallery/ajax_slider
      
      