---
sfSympalGallery:
  actAs: [sfSympalContentTypeTemplate]
  columns:
    title:
      type: string(255)
    thumb_width: integer(3)
    thumb_height: integer(3)
    renderer: string(255)
  relations:
    Assets:
      class: sfSympalAsset
      local: gallery_id
      foreign: asset_id
      refClass: sfSympalGalleryAsset
      foreignAlias: Galleries

sfSympalGalleryAsset:
  actAs: [sfSympalContentTypeTemplate]
  columns:
    title: string(255)
    url: string(255)
    gallery_id:
      type: integer
      primary: true
    asset_id:
      type: integer
      primary: true
  relations:
    Gallery:
      type: one
      class: sfSympalGallery
      local: gallery_id
      onDelete: CASCADE
      foreignAlias: GalleryAsset
    Asset:
      type: one
      class: sfSympalAsset
      local: asset_id
      onDelete: CASCADE
      foreignAlias: GalleryAsset    